//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MotelManagerEntities : DbContext
    {
        internal object motelrooms;
        internal object roomranges;

        public MotelManagerEntities()
            : base("name=MotelManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<MOTELROOM> MOTELROOMs { get; set; }
        public virtual DbSet<PARTICULARSERVICE> PARTICULARSERVICEs { get; set; }
        public virtual DbSet<REINTINFOR> REINTINFORs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<ROOMRANGE> ROOMRANGEs { get; set; }
        public virtual DbSet<ROOMRANK> ROOMRANKs { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
