//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTELROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOTELROOM()
        {
            this.BILLs = new HashSet<BILL>();
            this.REINTINFORs = new HashSet<REINTINFOR>();
        }
    
        public int ID { get; set; }
        public string RoomName { get; set; }
        public Nullable<bool> StateRoom { get; set; }
        public Nullable<int> IDRoomRank { get; set; }
        public Nullable<int> IDRoomRange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ROOMRANGE ROOMRANGE { get; set; }
        public virtual ROOMRANK ROOMRANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REINTINFOR> REINTINFORs { get; set; }
    }
}
