//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class REINTINFOR
    {
        public string IDCustomer { get; set; }
        public int IDRoom { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual MOTELROOM MOTELROOM { get; set; }
    }
}
